spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DATABASE_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASS}
    application:
        name: cardgameserver
    jpa:
      hibernate:
        ddl-auto: validate
    liquibase:
      change-log: db/master.xml
    web:
      resources:
        static-locations:
          - classpath:/static/
          - file:${UPLOADS_LOCATION}
    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 5MB